import { useEffect, useState } from "react";
import { QueryClient, QueryClientProvider } from "react-query";
import { AppProps } from "next/app";
import Head from "next/head";
import { useRouter } from "next/router";
import Layout from "../components/layout/Layout";
import Notifications from "../components/elements/Notifications";
import { SocketContext, socketContextObj } from "../context/socket";
import "../styles/globals.css";

require("../styles/antd-variables.less");

const queryClient = new QueryClient();

const MyApp = ({ Component, pageProps }: AppProps) => {
  const [isLoading, setIsLoading] = useState(false);
  const Router = useRouter();
  const [socket, setSocket] = useState(socketContextObj.socket);

  const socketValues = { socket, setSocket };

  useEffect(() => {
    Router.events.on("routeChangeStart", () => setIsLoading(true));
    Router.events.on("routeChangeComplete", () => setIsLoading(false));
    Router.events.on("routeChangeError", () => setIsLoading(false));
  }, [Router.events]);

  return (
    <SocketContext.Provider value={socketValues}>
      <QueryClientProvider client={queryClient}>
        <Head>
          <title>Sparrow Reference Web App</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
        </Head>
        <Layout isLoading={isLoading}>
          <Notifications items={[]} />
          <Component {...pageProps} />
        </Layout>
      </QueryClientProvider>
    </SocketContext.Provider>
  );
};

export default MyApp;
